# Generated by Django 4.2.1 on 2024-04-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('is_first', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
            ],
        ),
    ]
