# Generated by Django 4.2.1 on 2024-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesForEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='education_materials',
            name='file',
        ),
        migrations.AddField(
            model_name='education_materials',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='Study.filesforex'),
        ),
    ]
