# Generated by Django 4.2.1 on 2024-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0002_education_materials_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_education_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='education_materials',
            name='is_first',
        ),
        migrations.RemoveField(
            model_name='education_materials',
            name='is_last',
        ),
    ]
