# Generated by Django 4.2.1 on 2024-04-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0003_type_of_education_materials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules_of_education_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='education_materials',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Study.type_of_education_materials'),
        ),
        migrations.AddField(
            model_name='education_materials',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Study.modules_of_education_materials'),
        ),
    ]
