# Generated by Django 4.2.1 on 2024-04-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0003_filesforex_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_materials',
            name='files',
            field=models.ManyToManyField(blank=True, to='Study.filesforex'),
        ),
    ]
