# Generated by Django 4.2.1 on 2024-04-11 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Study', '0004_alter_education_materials_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_materials',
            name='must_req',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='CompletedEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('education_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study.education_materials')),
                ('files', models.ManyToManyField(blank=True, to='Study.filesforex')),
                ('student', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
