# Generated by Django 4.2.1 on 2024-04-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0004_modules_of_education_materials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education_materials',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='education_materials',
            old_name='type_id',
            new_name='type',
        ),
    ]
