# Generated by Django 4.2.1 on 2024-04-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0005_rename_module_id_education_materials_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules_of_education_materials',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modules_of_education_materials',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
