# Generated by Django 4.2.1 on 2024-04-11 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Study', '0005_education_materials_must_req_completedex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedex',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
