# Generated by Django 4.2.1 on 2024-04-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0006_modules_of_education_materials_is_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules_of_education_materials',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
