# Generated by Django 4.2.1 on 2024-04-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0007_modules_of_education_materials_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections_of_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Study.modules_of_education_materials'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Study.type_of_education_materials'),
        ),
        migrations.AddField(
            model_name='modules_of_education_materials',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Study.sections_of_modules'),
        ),
    ]
