# Generated by Django 4.2.1 on 2024-04-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0008_alter_completedex_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedex',
            name='files',
        ),
        migrations.AddField(
            model_name='completedex',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
