# Generated by Django 4.2.1 on 2024-04-11 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Study', '0009_remove_completedex_files_completedex_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedex',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.RemoveField(
            model_name='completedex',
            name='student',
        ),
        migrations.AddField(
            model_name='completedex',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
