# Generated by Django 4.2.1 on 2024-04-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0010_alter_completedex_file_remove_completedex_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedex',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedex',
            name='grade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
