# Generated by Django 4.2.1 on 2024-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0011_completedex_date_created_alter_completedex_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedex',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
