# Generated by Django 4.2.1 on 2024-04-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0015_remove_completedex_files_completedex_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedex',
            name='file',
        ),
        migrations.AddField(
            model_name='completedex',
            name='files',
            field=models.ManyToManyField(blank=True, to='Study.filesforex'),
        ),
    ]
