# Generated by Django 4.2.1 on 2024-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0016_remove_completedex_file_completedex_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedex',
            name='files',
        ),
        migrations.AddField(
            model_name='completedex',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
