# Generated by Django 4.2.1 on 2024-04-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0017_remove_completedex_files_completedex_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education_materials',
            name='must_req',
        ),
    ]
