# Generated by Django 4.2.1 on 2024-05-18 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Study', '0018_remove_education_materials_must_req'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedex',
            options={'verbose_name': 'Работы студентов'},
        ),
        migrations.AlterModelOptions(
            name='education_materials',
            options={'verbose_name': 'Учебные материалы'},
        ),
        migrations.AlterModelOptions(
            name='filesforex',
            options={'verbose_name': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='modules_of_education_materials',
            options={'verbose_name': 'Модуль обучения'},
        ),
        migrations.AlterModelOptions(
            name='sections_of_modules',
            options={'verbose_name': 'Раздел обучения'},
        ),
        migrations.AlterModelOptions(
            name='type_of_education_materials',
            options={'verbose_name': 'Тип материала'},
        ),
        migrations.RemoveField(
            model_name='modules_of_education_materials',
            name='is_first',
        ),
        migrations.RemoveField(
            model_name='modules_of_education_materials',
            name='is_last',
        ),
        migrations.AddField(
            model_name='sections_of_modules',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sections_of_modules',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='files',
            field=models.ManyToManyField(blank=True, to='Study.filesforex', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Study.modules_of_education_materials', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='education_materials',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Study.type_of_education_materials', verbose_name='Тип'),
        ),
    ]
