# Generated by Django 4.2.1 on 2024-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0019_alter_completedex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='message',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
