# Generated by Django 4.2.1 on 2024-05-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0021_choise_questionfortest_studytest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytest',
            name='question',
        ),
        migrations.AddField(
            model_name='studytest',
            name='question',
            field=models.ManyToManyField(blank=True, to='Study.questionfortest'),
        ),
    ]
