# Generated by Django 4.2.1 on 2024-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0023_education_materials_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedex',
            name='count_correct_test',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
