# Generated by Django 4.2.1 on 2024-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0024_completedex_count_correct_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedex',
            name='count_quests',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
