# Generated by Django 4.2.1 on 2024-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0026_completedex_finish_completedex_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedex',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='completedex',
            name='start',
        ),
        migrations.AddField(
            model_name='education_materials',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education_materials',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
