# Generated by Django 4.2.1 on 2024-04-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='study_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Login.studentgroup'),
        ),
    ]
