# Generated by Django 4.2.1 on 2024-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_studentgroup_user_study_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curse',
            field=models.IntegerField(default=0),
        ),
    ]
