# Generated by Django 4.2.1 on 2024-05-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_user_curse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
