# Generated by Django 4.2.1 on 2024-05-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curse',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Login.studentgroup'),
        ),
    ]
